[build]
  publish = "dist"
  command = "npm run build'"

[dev]
  framework = "#static"

[[headers]]
  for = "/*"
  [headers.values]
    # Required for SharedArrayBuffer (if Pyodide needs it for some features)
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
